# Generated by Django 4.1.4 on 2022-12-30 22:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_routine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='reps',
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_routine.workout')),
            ],
        ),
    ]
