# Generated by Django 4.1.4 on 2024-07-29 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_routine', '0002_remove_workout_reps_workoutset'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 0, 26, 26, 463139, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
