# Generated by Django 4.1.4 on 2024-07-29 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_routine', '0003_workout_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
