version: "3"

services:
  rep-tracker:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    ports:
      - 8000:8000
    volumes:
      - .:/var/apps/rep_tracker
